// Miniatures data
const miniaturesData = [
  {
    id: 1,
    nombre: "Don Quijote de La Mancha",
    descripcion: "Busto de Don Quijote, escultura por Ogareg Miniatures.",
    fecha: "Septiembre 2025",
    reconocimientos: ["Freak Wars 2025 - Oro en Busto Standard", "Ceramic Brush 2025 - Entrada Notable"],
    tipo: "Miniaturas",
    imagenPrincipal: "public/images/quijote/main.jpg",
    imagenes: ["public/images/quijote/1.jpg", "public/images/quijote/2.jpg", "public/images/quijote/3.jpg", "public/images/quijote/4.jpg",
      "public/images/quijote/1w.jpg", "public/images/quijote/2w.jpg", "public/images/quijote/3w.jpg", "public/images/quijote/4w.jpg"
    ],
  },
  {
    id: 2,
    nombre: "Mandaloriano",
    descripcion:
      "Mi interpretación pintada del icónico busto del Mandaloriano (Din Djarin) de la serie Star Wars. El enfoque principal fue lograr texturas metálicas realistas para la armadura Beskar y aplicar efectos de desgaste (polvo, desconchones) para reflejar sus duras travesías. Este es el camino. Escultura por SkullHill",
    fecha: "Marzo 2025",
    reconocimientos: ["Freak Wars 2025 - Oro en Busto Standard", "Ceramic Brush 2025 - Entrada Notable"],
    tipo: "Miniaturas",
    imagenPrincipal: "public/images/mandalorian/main.jpg",
    imagenes: [
      "public/images/mandalorian/1.jpg",
      "public/images/mandalorian/2.jpg",
      "public/images/mandalorian/3.jpg",
      "public/images/mandalorian/4.jpg",
      "public/images/mandalorian/5.jpg",
      "public/images/mandalorian/6.jpg",
      "public/images/mandalorian/7.jpg"
    ],
  },
  {
    id: 3,
    nombre: "Aries",
    descripcion: "Figura de Aries esculpida por Joapala para Scale75. Fue un reto realizar la base con masilla y jugar con la iluminación del fuego.",
    fecha: "Agosto 2025",
    reconocimientos: ["Freak Wars 2025 - Plata en Miniatura Individual"],
    tipo: "Miniaturas",
    imagenPrincipal: "public/images/aries/main.jpg",
    imagenes: [
      "public/images/aries/1.jpg",
      "public/images/aries/2.jpg",
      "public/images/aries/3.jpg",
      "public/images/aries/4.jpg",
      "public/images/aries/5.jpg",
      "public/images/aries/6.jpg",
      "public/images/aries/7.jpg"
    ],
  },
  {
    id: 4,
    nombre: "Alice Cross",
    descripcion: "Figura de Alice Cross de Neko Galaxy, esculpida por Anna Kartashova.",
    fecha: "Mayo 2025",
    reconocimientos: ["Freak Wars 2025 - Oro"],
    tipo: "Miniaturas",
    imagenPrincipal: "public/images/alice/main.jpg",
    imagenes: [
      "public/images/alice/1.jpg",
      "public/images/alice/2.jpg",
      "public/images/alice/3.jpg"
    ],
  },
  {
    id: 5,
    nombre: "Grand Moff Tarkin",
    descripcion: "Busto del Grand Moff Tarkin, personaje de Star Wars. Escultura por Sidnaique.",
    fecha: "Marzo 2025",
    reconocimientos: ["Freak Wars 2025 - Oro"],
    tipo: "Miniaturas",
    imagenPrincipal: "public/images/mofftarkin/main.jpg",
    imagenes: [
      "public/images/mofftarkin/1.jpg",
      "public/images/mofftarkin/2.jpg",
      "public/images/mofftarkin/3.jpg",
      "public/images/mofftarkin/4.jpg",
      "public/images/mofftarkin/5.jpg"
    ],
  },
  {
    id: 6,
    nombre: "Darkoath Chieftain",
    descripcion: "Caudillo bárbaro de los Darkoath para Age of Sigmar. Trabajo detallado en los tonos de piel y dorado de adornos.",
    fecha: "Septiembre 2024",
    reconocimientos: [],
    tipo: "Warhammer",
    imagenPrincipal: "public/images/darkoath/main.jpg",
    imagenes: [
      "public/images/darkoath/1.jpg",
      "public/images/darkoath/2.jpg",
    ],
  },
  {
    id: 7,
    nombre: "Mando & Grogu Diorama",
    descripcion: "Diorama representando a Din Djarin y Grogu. Enfoque en el contraste entre la armadura brillante de Beskar y el terreno boscoso.",
    fecha: "Julio 2024",
    reconocimientos: [],
    tipo: "Warhammer",
    imagenPrincipal: "public/images/mandogrogu/main.jpg",
    imagenes: [
      "public/images/mandogrogu/1.jpg",
      "public/images/mandogrogu/2.jpg",
      "public/images/mandogrogu/3.jpg",
      "public/images/mandogrogu/4.jpg",
      "public/images/mandogrogu/5.jpg",
      "public/images/mandogrogu/6.jpg",
    ],
  },
  {
    id: 8,
    nombre: "Jefe de Guerra Orco",
    descripcion: "Imponente líder Orco listo para la batalla. Pintado con técnicas de weathering intenso para simular óxido y arañazos en la armadura.",
    fecha: "Diciembre 2023",
    reconocimientos: [],
    tipo: "Warhammer",
    imagenPrincipal: "public/images/orkwarboss/main.jpg",
    imagenes: [
      "public/images/orkwarboss/1.jpg",
      "public/images/orkwarboss/2.jpg",
      "public/images/orkwarboss/3.jpg",
      "public/images/orkwarboss/4.jpg",
      "public/images/orkwarboss/5.jpg",
      "public/images/orkwarboss/6.jpg",
      "public/images/orkwarboss/7.jpg",
    ],
  },
  {
    id: 9,
    nombre: "Grotmas Gitz",
    descripcion: "Escena festiva de Goblins llena de carácter. Colores vibrantes y saturados para destacar el tono humorístico de la miniatura.",
    fecha: "Junio 2024",
    reconocimientos: [],
    tipo: "Warhammer",
    imagenPrincipal: "public/images/grotmas/main.jpg",
    imagenes: [
      "public/images/grotmas/1.jpg",
      "public/images/grotmas/2.jpg",
      "public/images/grotmas/3.jpg",
      "public/images/grotmas/4.jpg",
      "public/images/grotmas/5.jpg",
      "public/images/grotmas/6.jpg",
      "public/images/grotmas/7.jpg",
      "public/images/grotmas/8.jpg"
    ],
  },
  {
    id: 10,
    nombre: "The River Gobbo",
    descripcion: "Figura de Workshop situada en una zona pantanosa. Destaca el trabajo en la armadura metálica desgastada, con efectos de óxido y reflejos del río en el metal.",
    fecha: "Octubre 2025",
    reconocimientos: [],
    tipo: "Warhammer",
    imagenPrincipal: "public/images/rivergobbo/main.jpg",
    imagenes: [
      "public/images/rivergobbo/1.jpg",
      "public/images/rivergobbo/2.jpg",
      "public/images/rivergobbo/3.jpg"
    ],
  },
  {
    id: 11,
    nombre: "(Not) Self Portrait 1887",
    descripcion: "Busto de Van Gogh, esculpido por Selfix. El objetivo era simular el estilo de Van Gogh en su Autoretrato de 1887.",
    fecha: "Noviembre 2025",
    reconocimientos: [],
    tipo: "Miniaturas",
    imagenPrincipal: "public/images/vangogh/main.jpg",
    imagenes: [
      "public/images/vangogh/1.jpg",
      "public/images/vangogh/2.jpg",
      "public/images/vangogh/3.jpg",
      "public/images/vangogh/4.jpg",
      "public/images/vangogh/5.jpg",
      "public/images/vangogh/6.jpg",
    ],
  },
  {
    id: 12,
    nombre: "Scorpio",
    descripcion: "Busto Scorpio de Yedharo. Este busto está ambientado en una noche estrellada con una iluminación de un fuego por la parte derecha ",
    fecha: "Enero 2024",
    reconocimientos: [],
    tipo: "Miniaturas",
    imagenPrincipal: "public/images/scorpio/main.jpg",
    imagenes: [
      "public/images/scorpio/1.jpg",
      "public/images/scorpio/2.jpg",
      "public/images/scorpio/3.jpg",
    ],
  },
]
